-- 사용자 생성
INSERT INTO users (created_at, updated_at, user_role, user_status, nickname, introduce, username, password)
VALUES (now(), now(), 'ROLE_USER', 'STATUS_NORMAL', '홍길동1', '안녕', 'user1', '$2a$12$AER7FlPMh.yjwuoDZ.k2SeTkNazFQTyJXrCHTSKeW1F.pe95nZVPK'),
       (now(), now(), 'ROLE_USER', 'STATUS_NORMAL', '홍길동2', '안녕', 'user2', '$2a$12$AER7FlPMh.yjwuoDZ.k2SeTkNazFQTyJXrCHTSKeW1F.pe95nZVPK'),
       (now(), now(), 'ROLE_USER', 'STATUS_NORMAL', '홍길동3', '안녕', 'user3', '$2a$12$AER7FlPMh.yjwuoDZ.k2SeTkNazFQTyJXrCHTSKeW1F.pe95nZVPK'),
       (now(), now(), 'ROLE_USER', 'STATUS_NORMAL', '홍길동4', '안녕', 'user4', '$2a$12$AER7FlPMh.yjwuoDZ.k2SeTkNazFQTyJXrCHTSKeW1F.pe95nZVPK'),
       (now(), now(), 'ROLE_USER', 'STATUS_NORMAL', '홍길동5', '안녕', 'user5', '$2a$12$AER7FlPMh.yjwuoDZ.k2SeTkNazFQTyJXrCHTSKeW1F.pe95nZVPK');

-- 음식점 생성
INSERT INTO restaurants (created_at, updated_at, address, description, name, category, users_id, like_count)
VALUES (now(), now(), '주소1', '소개1', '가게이름1', 'KOREAN', 5, 1),
       (now(), now(), '주소2', '소개2', '가게이름2', 'KOREAN', 5, 1),
       (now(), now(), '주소3', '소개3', '가게이름3', 'KOREAN', 5, 1),
       (now(), now(), '주소4', '소개4', '가게이름4', 'KOREAN', 5, 1),
       (now(), now(), '주소5', '소개5', '가게이름5', 'KOREAN', 5, 1),
       (now(), now(), '주소6', '소개6', '가게이름6', 'KOREAN', 5, 1),
       (now(), now(), '주소7', '소개7', '가게이름7', 'KOREAN', 5, 1),
       (now(), now(), '주소8', '소개8', '가게이름8', 'KOREAN', 5, 1),
       (now(), now(), '주소9', '소개9', '가게이름9', 'KOREAN', 5, 1),
       (now(), now(), '주소10', '소개10', '가게이름10', 'KOREAN', 5, 1),
       (now(), now(), '주소11', '소개11', '가게이름11', 'KOREAN', 5, 1),
       (now(), now(), '주소12', '소개12', '가게이름12', 'KOREAN', 5, 1),
       (now(), now(), '주소13', '소개13', '가게이름13', 'KOREAN', 5, 1),
       (now(), now(), '주소14', '소개14', '가게이름14', 'KOREAN', 5, 1),
       (now(), now(), '주소15', '소개15', '가게이름15', 'KOREAN', 5, 1),
       (now(), now(), '주소16', '소개16', '가게이름16', 'KOREAN', 5, 1),
       (now(), now(), '주소17', '소개17', '가게이름17', 'KOREAN', 5, 1),
       (now(), now(), '주소18', '소개18', '가게이름18', 'KOREAN', 5, 1),
       (now(), now(), '주소19', '소개19', '가게이름19', 'KOREAN', 5, 1),
       (now(), now(), '주소20', '소개20', '가게이름20', 'KOREAN', 5, 1),
       (now(), now(), '주소21', '소개21', '가게이름21', 'KOREAN', 5, 1),
       (now(), now(), '주소22', '소개22', '가게이름22', 'KOREAN', 5, 1),
       (now(), now(), '주소23', '소개23', '가게이름23', 'KOREAN', 5, 1),
       (now(), now(), '주소24', '소개24', '가게이름24', 'KOREAN', 5, 1),
       (now(), now(), '주소25', '소개25', '가게이름25', 'KOREAN', 5, 1),
       (now(), now(), '주소26', '소개26', '가게이름26', 'KOREAN', 5, 1),
       (now(), now(), '주소27', '소개27', '가게이름27', 'KOREAN', 5, 1),
       (now(), now(), '주소28', '소개28', '가게이름28', 'KOREAN', 5, 1),
       (now(), now(), '주소29', '소개29', '가게이름29', 'KOREAN', 5, 1),
       (now(), now(), '주소30', '소개30', '가게이름30', 'KOREAN', 5, 1),
       (now(), now(), '주소31', '소개31', '가게이름31', 'KOREAN', 5, 1),
       (now(), now(), '주소32', '소개32', '가게이름32', 'KOREAN', 5, 1),
       (now(), now(), '주소33', '소개33', '가게이름33', 'KOREAN', 5, 1),
       (now(), now(), '주소34', '소개34', '가게이름34', 'KOREAN', 5, 1),
       (now(), now(), '주소35', '소개35', '가게이름35', 'KOREAN', 5, 1),
       (now(), now(), '주소36', '소개36', '가게이름36', 'KOREAN', 5, 1),
       (now(), now(), '주소37', '소개37', '가게이름37', 'KOREAN', 5, 1),
       (now(), now(), '주소38', '소개38', '가게이름38', 'KOREAN', 5, 1),
       (now(), now(), '주소39', '소개39', '가게이름39', 'KOREAN', 5, 1),
       (now(), now(), '주소40', '소개40', '가게이름40', 'KOREAN', 5, 1),
       (now(), now(), '주소41', '소개41', '가게이름41', 'KOREAN', 5, 1),
       (now(), now(), '주소42', '소개42', '가게이름42', 'KOREAN', 5, 1),
       (now(), now(), '주소43', '소개43', '가게이름43', 'KOREAN', 5, 1),
       (now(), now(), '주소44', '소개44', '가게이름44', 'KOREAN', 5, 1),
       (now(), now(), '주소45', '소개45', '가게이름45', 'KOREAN', 5, 1),
       (now(), now(), '주소46', '소개46', '가게이름46', 'KOREAN', 5, 1),
       (now(), now(), '주소47', '소개47', '가게이름47', 'KOREAN', 5, 1),
       (now(), now(), '주소48', '소개48', '가게이름48', 'KOREAN', 5, 1),
       (now(), now(), '주소49', '소개49', '가게이름49', 'KOREAN', 5, 1),
       (now(), now(), '주소50', '소개50', '가게이름50', 'KOREAN', 5, 1),
       (now(), now(), '주소51', '소개51', '가게이름51', 'KOREAN', 5, 1),
       (now(), now(), '주소52', '소개52', '가게이름52', 'KOREAN', 5, 1),
       (now(), now(), '주소53', '소개53', '가게이름53', 'KOREAN', 5, 1);

-- 리뷰 생성
INSERT INTO reviews(created_at, updated_at, rating, comment, restaurants_id, users_id, like_count)
VALUES (now(), now(), 3, '댓글내용1', 1, 5, 1),
       (now(), now(), 5, '댓글내용2', 1, 5, 1),
       (now(), now(), 3, '댓글내용3', 1, 5, 1),
       (now(), now(), 2, '댓글내용4', 1, 5, 1),
       (now(), now(), 2, '댓글내용5', 1, 5, 1),
       (now(), now(), 5, '댓글내용6', 1, 5, 1),
       (now(), now(), 3, '댓글내용7', 1, 5, 1),
       (now(), now(), 4, '댓글내용8', 1, 5, 1),
       (now(), now(), 2, '댓글내용9', 1, 5, 1),
       (now(), now(), 3, '댓글내용10', 1, 5, 1),
       (now(), now(), 3, '댓글내용11', 1, 5, 1),
       (now(), now(), 2, '댓글내용12', 1, 5, 1),
       (now(), now(), 3, '댓글내용13', 1, 5, 1),
       (now(), now(), 2, '댓글내용14', 1, 5, 1),
       (now(), now(), 4, '댓글내용15', 1, 5, 1),
       (now(), now(), 3, '댓글내용16', 1, 5, 1),
       (now(), now(), 3, '댓글내용17', 1, 5, 1),
       (now(), now(), 2, '댓글내용18', 1, 5, 1),
       (now(), now(), 2, '댓글내용19', 1, 5, 1),
       (now(), now(), 5, '댓글내용20', 1, 5, 1),
       (now(), now(), 4, '댓글내용21', 1, 5, 1),
       (now(), now(), 1, '댓글내용22', 1, 5, 1),
       (now(), now(), 4, '댓글내용23', 1, 5, 1),
       (now(), now(), 1, '댓글내용24', 1, 5, 1),
       (now(), now(), 2, '댓글내용25', 1, 5, 1),
       (now(), now(), 1, '댓글내용26', 1, 5, 1),
       (now(), now(), 2, '댓글내용27', 1, 5, 1),
       (now(), now(), 2, '댓글내용28', 1, 5, 1),
       (now(), now(), 4, '댓글내용29', 1, 5, 1),
       (now(), now(), 2, '댓글내용30', 1, 5, 1),
       (now(), now(), 3, '댓글내용31', 1, 5, 1),
       (now(), now(), 2, '댓글내용32', 1, 5, 1),
       (now(), now(), 1, '댓글내용33', 1, 5, 1),
       (now(), now(), 5, '댓글내용34', 1, 5, 1),
       (now(), now(), 4, '댓글내용35', 1, 5, 1),
       (now(), now(), 2, '댓글내용36', 1, 5, 1),
       (now(), now(), 2, '댓글내용37', 1, 5, 1),
       (now(), now(), 3, '댓글내용38', 1, 5, 1),
       (now(), now(), 4, '댓글내용39', 1, 5, 1),
       (now(), now(), 4, '댓글내용40', 1, 5, 1),
       (now(), now(), 1, '댓글내용41', 1, 5, 1),
       (now(), now(), 5, '댓글내용42', 1, 5, 1),
       (now(), now(), 5, '댓글내용43', 1, 5, 1),
       (now(), now(), 3, '댓글내용44', 1, 5, 1),
       (now(), now(), 4, '댓글내용45', 1, 5, 1),
       (now(), now(), 4, '댓글내용46', 1, 5, 1),
       (now(), now(), 1, '댓글내용47', 1, 5, 1),
       (now(), now(), 1, '댓글내용48', 1, 5, 1),
       (now(), now(), 5, '댓글내용49', 1, 5, 1),
       (now(), now(), 2, '댓글내용50', 1, 5, 1),
       (now(), now(), 5, '댓글내용51', 1, 5, 1),
       (now(), now(), 1, '댓글내용52', 1, 5, 1),
       (now(), now(), 2, '댓글내용53', 1, 5, 1);

-- 좋아요 추가. 음식점과 리뷰의 1번은 좋아요 추가 안함
INSERT INTO likes (created_at, updated_at, users_id, contents_id, content_type)
VALUES (now(), now(), 1, 2, 'RESTAURANT'),
       (now(), now(), 1, 3, 'RESTAURANT'),
       (now(), now(), 1, 4, 'RESTAURANT'),
       (now(), now(), 1, 5, 'RESTAURANT'),
       (now(), now(), 1, 6, 'RESTAURANT'),
       (now(), now(), 1, 7, 'RESTAURANT'),
       (now(), now(), 1, 8, 'RESTAURANT'),
       (now(), now(), 1, 9, 'RESTAURANT'),
       (now(), now(), 1, 10, 'RESTAURANT'),
       (now(), now(), 1, 11, 'RESTAURANT'),
       (now(), now(), 1, 12, 'RESTAURANT'),
       (now(), now(), 1, 13, 'RESTAURANT'),
       (now(), now(), 1, 14, 'RESTAURANT'),
       (now(), now(), 1, 15, 'RESTAURANT'),
       (now(), now(), 1, 16, 'RESTAURANT'),
       (now(), now(), 1, 17, 'RESTAURANT'),
       (now(), now(), 1, 18, 'RESTAURANT'),
       (now(), now(), 1, 19, 'RESTAURANT'),
       (now(), now(), 1, 20, 'RESTAURANT'),
       (now(), now(), 1, 21, 'RESTAURANT'),
       (now(), now(), 1, 22, 'RESTAURANT'),
       (now(), now(), 1, 23, 'RESTAURANT'),
       (now(), now(), 1, 24, 'RESTAURANT'),
       (now(), now(), 1, 25, 'RESTAURANT'),
       (now(), now(), 1, 26, 'RESTAURANT'),
       (now(), now(), 1, 27, 'RESTAURANT'),
       (now(), now(), 1, 28, 'RESTAURANT'),
       (now(), now(), 1, 29, 'RESTAURANT'),
       (now(), now(), 1, 30, 'RESTAURANT'),
       (now(), now(), 1, 31, 'RESTAURANT'),
       (now(), now(), 1, 32, 'RESTAURANT'),
       (now(), now(), 1, 33, 'RESTAURANT'),
       (now(), now(), 1, 34, 'RESTAURANT'),
       (now(), now(), 1, 35, 'RESTAURANT'),
       (now(), now(), 1, 36, 'RESTAURANT'),
       (now(), now(), 1, 37, 'RESTAURANT'),
       (now(), now(), 1, 38, 'RESTAURANT'),
       (now(), now(), 1, 39, 'RESTAURANT'),
       (now(), now(), 1, 40, 'RESTAURANT'),
       (now(), now(), 1, 41, 'RESTAURANT'),
       (now(), now(), 1, 42, 'RESTAURANT'),
       (now(), now(), 1, 43, 'RESTAURANT'),
       (now(), now(), 1, 44, 'RESTAURANT'),
       (now(), now(), 1, 45, 'RESTAURANT'),
       (now(), now(), 1, 46, 'RESTAURANT'),
       (now(), now(), 1, 47, 'RESTAURANT'),
       (now(), now(), 1, 48, 'RESTAURANT'),
       (now(), now(), 1, 49, 'RESTAURANT'),
       (now(), now(), 1, 50, 'RESTAURANT'),
       (now(), now(), 1, 51, 'RESTAURANT'),
       (now(), now(), 1, 52, 'RESTAURANT'),
       (now(), now(), 1, 53, 'RESTAURANT'),
       (now(), now(), 1, 2, 'REVIEW'),
       (now(), now(), 1, 3, 'REVIEW'),
       (now(), now(), 1, 4, 'REVIEW'),
       (now(), now(), 1, 5, 'REVIEW'),
       (now(), now(), 1, 6, 'REVIEW'),
       (now(), now(), 1, 7, 'REVIEW'),
       (now(), now(), 1, 8, 'REVIEW'),
       (now(), now(), 1, 9, 'REVIEW'),
       (now(), now(), 1, 10, 'REVIEW'),
       (now(), now(), 1, 11, 'REVIEW'),
       (now(), now(), 1, 12, 'REVIEW'),
       (now(), now(), 1, 13, 'REVIEW'),
       (now(), now(), 1, 14, 'REVIEW'),
       (now(), now(), 1, 15, 'REVIEW'),
       (now(), now(), 1, 16, 'REVIEW'),
       (now(), now(), 1, 17, 'REVIEW'),
       (now(), now(), 1, 18, 'REVIEW'),
       (now(), now(), 1, 19, 'REVIEW'),
       (now(), now(), 1, 20, 'REVIEW'),
       (now(), now(), 1, 21, 'REVIEW'),
       (now(), now(), 1, 22, 'REVIEW'),
       (now(), now(), 1, 23, 'REVIEW'),
       (now(), now(), 1, 24, 'REVIEW'),
       (now(), now(), 1, 25, 'REVIEW'),
       (now(), now(), 1, 26, 'REVIEW'),
       (now(), now(), 1, 27, 'REVIEW'),
       (now(), now(), 1, 28, 'REVIEW'),
       (now(), now(), 1, 29, 'REVIEW'),
       (now(), now(), 1, 30, 'REVIEW'),
       (now(), now(), 1, 31, 'REVIEW'),
       (now(), now(), 1, 32, 'REVIEW'),
       (now(), now(), 1, 33, 'REVIEW'),
       (now(), now(), 1, 34, 'REVIEW'),
       (now(), now(), 1, 35, 'REVIEW'),
       (now(), now(), 1, 36, 'REVIEW'),
       (now(), now(), 1, 37, 'REVIEW'),
       (now(), now(), 1, 38, 'REVIEW'),
       (now(), now(), 1, 39, 'REVIEW'),
       (now(), now(), 1, 40, 'REVIEW'),
       (now(), now(), 1, 41, 'REVIEW'),
       (now(), now(), 1, 42, 'REVIEW'),
       (now(), now(), 1, 43, 'REVIEW'),
       (now(), now(), 1, 44, 'REVIEW'),
       (now(), now(), 1, 45, 'REVIEW'),
       (now(), now(), 1, 46, 'REVIEW'),
       (now(), now(), 1, 47, 'REVIEW'),
       (now(), now(), 1, 48, 'REVIEW'),
       (now(), now(), 1, 49, 'REVIEW'),
       (now(), now(), 1, 50, 'REVIEW'),
       (now(), now(), 1, 51, 'REVIEW'),
       (now(), now(), 1, 52, 'REVIEW'),
       (now(), now(), 1, 53, 'REVIEW');